analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1420133,\\n  \\"name\\"\: \\"SMILE\\",\\n  \\"teamId\\"\: 1400760,\\n  \\"organizationId\\"\: 1233533,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1400760\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.onpremise.enable=false
analytics.testcloud.hub.switchHub.enable=false
