analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1420133,\\n  \\"name\\"\: \\"SMILE\\",\\n  \\"teamId\\"\: 1400760,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 1400760,\\n    \\"name\\"\: \\"SMILE\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 1233533,\\n      \\"name\\"\: \\"Depdir API\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1400760,\\n  \\"name\\"\: \\"SMILE\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 1233533,\\n    \\"name\\"\: \\"Depdir API\\",\\n    \\"samlSSO\\"\: false\\n  }\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
