plugins {
  id 'java'
  id "com.katalon.gradle-plugin" version "0.1.2"
}

repositories {
  mavenCentral()
}

dependencies {
  // sample dependencies
  // rest-assured
  // compile 'io.rest-assured:rest-assured:3.2.0'
  // JsonPath
  // compile 'io.rest-assured:json-path:3.2.0'
  // XmlPath
  // compile 'io.rest-assured:json-path:3.2.0'
  // JSON Schema Validation
  // compile 'io.rest-assured:json-schema-validator:3.2.0'
  	implementation 'commons-codec:commons-codec:1.15'
    implementation 'org.apache.commons:commons-lang3:3.5'      
    implementation 'com.warrenstrange:googleauth:1.5.0'
    implementation 'com.bastiaanjansen:java-otp:0.4.0'
    implementation 'com.sun.mail:javax.mail:1.6.2'
}