<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Todolist_ApprovedTodolistPelayanan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f4da0d0f-a5a6-4208-b1d6-999fe02aa838</testSuiteGuid>
   <testCaseLink>
      <guid>9d20652e-fa05-47a6-8bd5-ae2c48d22fc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/12-Tugas Hari Ini/SMTC_TugasHariIni_35-PMPApprovedKlaimJKK_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a297608-1e34-4eb8-89e5-81706b58ce93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5edf69f-d44d-409a-ab56-73d51462294a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feffc5fb-5a89-4db9-ac05-3a8afc2b634e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>833f9a45-9b38-44a7-948d-fa81d6443bc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69f4762b-4727-4b21-8de0-b20779b2ad65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0efe8f81-a025-4e81-bdf8-3b93a49f89c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42da5bd6-838d-433a-a31f-25a06bddcefe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42404f00-f492-4c0c-91ad-22cc1bb696ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35d48630-d0c7-48ba-a776-37d130e53c67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ba6070-1b73-4767-b19c-685ef9cf273f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74713d18-a8bc-4e0f-8418-4cbbd17f25e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a888d97-5b29-40b4-818c-2ed4b81e9e1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/12-Tugas Hari Ini/SMTC_TugasHariIni_36-KBKEUpprovedKlaimMajemukJakon_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59d28f5d-9cd6-4cd9-aa8e-e631f723134f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76c739ce-6260-4462-a2db-23190e5fd034</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a3b592b-61fb-475d-83bd-55fef4fa61ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05dd138a-bf8c-4d23-a023-4ca7a469c035</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b90907-a013-46fc-a4f0-ff655d90d446</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112c0eda-d50b-4e66-b259-bc2a66424532</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b0ecbc7-43bd-434d-b7f6-9cb8cc17a8ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24c5bc3a-5c2d-4fa5-985b-aba71ae253de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>576cda42-ddcf-4df9-95cd-4b106fa88b14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c265e9c2-c27f-4e49-b532-a5ea4475fa69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88a74002-b533-44c2-9e98-061ecc3a22ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1cad55a-5353-44fd-ac12-1b0455553af1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acff24d3-4d2d-4a71-8693-0fb8a77a7ee6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/12-Tugas Hari Ini/SMTC_TugasHariIni_37-KBKEUpprovedKlaimMajemukPU_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>933bf902-1b74-469c-8a2d-988c4060ca6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5b9be7-c51b-498b-b5ea-e7553a528ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88d2af92-d5c1-4337-8753-c89c281afd9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8901a7b5-880c-4f15-80f9-85add6a417dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06bb88fd-5dd0-4501-b635-53c77a4f0b53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57ba1346-6405-498e-b5f8-f1126fd17482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b658297-9766-4b39-9b40-54b421c57bd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9005248-5f12-4951-b7bb-c4c06ddef88c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a20a4470-faa0-4356-8b72-fdadb794b097</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f50218e5-5fe5-436a-8666-ce49cab867b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143a9be1-7ef8-46bf-88f9-cabe0cbfd9af</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
