<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_SetupAksesAplikasi_01-pengajuanOvertimeKolektif</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3fbbd28a-02d5-481c-9768-be8886bc4dc5</testSuiteGuid>
   <testCaseLink>
      <guid>290106f3-f61e-4fcc-83f1-efb6f3ac0fee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_01-POCviewSetupAplikasi_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae146267-f095-42b4-8b8b-6768a026df3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b3c6bc-8154-4d09-a401-b5d377d9faa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5004f406-febb-4632-ac35-96b80e2b8daf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_02-pengajuandiTampilkan_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e8201b27-a2f0-49f3-9165-80fd472ca72a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_03-pengajuanTanpaIsiForm_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7f5d2c5e-b338-407c-b475-fe8c46f41640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_04-pengajuanBatal_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c9779896-2028-4b40-81ee-040b63d9acc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_05-pengajuanBesok_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>225cf37b-c016-48a2-9859-56bae5be22e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_06-pengajuanMingguDepan_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70721097-ca3c-4a80-b4f7-29eb5c6ed84f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_07-pengajuanKemaren_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>24f6ae44-e1ff-4d7a-8e55-220a008f5677</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_08-pengajuanKemarenMingguDepan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>320e10bd-f300-41bf-9f40-549aefc93a9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_09-pengajuanSatuBulan_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c5e34f11-8e33-4066-b44f-a1ca693f7bc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_10-pengajuanLewatdariAkhirBulan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d007265a-b28a-4226-bea3-44deffdae046</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_11-keteranganPengajuan_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a75aae3-2fc5-47a7-8394-5fae69617cfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9856609d-17fd-4021-8377-a80f8ca8d951</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_12-uploadExcel_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>784fc511-9fd7-44c0-a756-2466a25d6eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_13-uploadExcelLebih2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b8a1316f-1096-494a-945f-7cf61d3092fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_14-uploadJPG2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5bcd743b-e8a4-412d-a768-0f39a8fbb1bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_15-uploadJPEGLebih2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ed14a874-39d8-4337-b3de-dda0d718b3cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_16-uploadPDFLebih2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>72c03052-d82a-4230-b46e-e7fe070cea96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_17-uploadFileJPG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>370826df-d350-4f6e-81c0-56ac1f26918a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_18-uploadFileJPEG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5cb4cf19-7722-499e-b209-18a56538704a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_19-uploadFilePDF_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>57e8a3f2-c092-467c-bf33-c133e7a20984</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_20-selectAllUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fcc8fee7-c778-4b1f-8dcf-0a0ca00a79e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_21-selectSingleUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b010f09b-0785-431d-a556-20b35f9089ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_22-cariUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a958a6f7-9336-4f2c-87ca-8e0483353a3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff5cb642-2f1b-4b22-be03-9babc8399cd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_23-cariNamaDepanUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0f9bcf-31e3-4879-8300-65d5f6d574d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69775670-c133-4988-bc92-746b00b14496</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_24-cariNamBelakangUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b0f878f-e012-4e44-9db9-492a5d29647a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0113f921-cc1e-4175-a6e7-011d25374fc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_25-cariAngkaKodeUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10056c2b-2b81-4ed4-bfef-e69d675e7ea3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8b12ac9-8716-4713-a194-4eb1d82d13c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_26-cariAlphabetKodeUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06597094-e519-4daa-be6b-f74c2ba8591b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d43168ee-f529-4a65-8282-41c06906cbad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_27-cariSembarangAngkaUser_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fff8e92-3a67-4ac6-8af1-99ddb8f05f74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c747b9e-2cf5-41ec-92d9-1b445143d8a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_28-cariSembarangAlphabetUser_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2601b10a-b9f9-47ac-8a0a-eaf31a102c3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4e4cdb3-6195-4b16-8f17-7a57a1bf5e54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_29-cariSpesialKarakter_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09edaff7-d48e-46d6-8d20-477538545dd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>290df4d1-f9f0-46a8-a535-54c55d0e6a6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_30-pengajuanTanpaUser_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aef961d-02b2-4af2-91c1-2f62d63258fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bc76ed6-b2f2-4b32-a7eb-4a0a9c7f3051</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52ebe1de-4282-448e-8815-bb64ae3f63c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_31-pengajuanPenataOperasionalCabangJPG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e004a0fc-65c9-42ac-b42f-d1b71eee502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c714b1d-36d2-45bc-82b6-d34d93466583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47925905-9dc0-4ea6-b46c-b2b5fb83e1af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8697331-daf5-46e3-96cc-021c443181cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_32-pengajuanDicekKepalaCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>685d3949-db7e-4856-bc47-12398b80f488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c89742d3-b19c-4a56-baac-a9331a5d9dfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7062a6cd-897f-4bae-9ef8-66ff267d8869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c19a4597-acfb-483f-88c1-d6623d335659</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17e4e120-cc8d-437c-a0cd-7316a6a5c08e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3d4d786-3539-4f39-be89-96579d418343</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_33-pengajuanDisetujuiKAKACAB_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30dabddb-7461-453c-8e54-84087153a6e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26e030a5-cc3f-4ee8-a3f4-1f9d79d961ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0df2625-2659-4433-8370-ff328905a9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35367558-557f-4998-98ca-d941a87dc25f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bee00dda-03bb-4884-9663-9241a0c7a68a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_34-cekDisetujuiOlehPenataCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdbf15e5-8b48-42da-9a71-a89064cce898</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_35-cekDisetujuiOlehWAKA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de49f4ea-a446-4d48-bcfb-a6cbd3ffdedc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de14f3ad-b038-4440-bdc0-b2501a8b1166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28876c51-32cb-4f28-b66c-f65e5d8410e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ef74cb9-40e7-4021-9ba1-20d5f53d080a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d00f047f-89e0-4867-a9a7-544fe97c8d7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd0bf3f1-4b2a-4783-9013-3a58dfdce1b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_36-cekDisetujuiOlehUSMK_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdb8163f-d9d3-4a08-b2b5-3316aca31992</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cba1297-c9af-47ff-b3d5-65ec0a550211</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c27a48d5-79e8-4bbb-8ee1-9d9b4bc7454e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b8d6483-897a-4bfb-8c42-120b3ffb3f39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22cccd8a-4277-4452-97c9-bbc2bed6b4f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87caa8b8-5aba-4eb4-ab68-6cac1fea328c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_37-cekDisetujuiOlehUserSelectedCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e45d555-80ac-44b5-a0f3-814b5f154505</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08266b0f-c5d1-4c42-88f6-af7ad6184868</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ca9c19f-9dc1-43ed-b8f6-abbeafd82539</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6016b32-c2cf-4e60-aeb1-ae995aa064ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13821368-675d-4fc1-a6f5-b372f4d66a5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dbafb81-5836-4029-a1d6-3c75fed7a1e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33a5905f-f6fd-45f3-85f0-7dd76459e812</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_38-pengajuanDenganUserNPeriodeSama_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae146267-f095-42b4-8b8b-6768a026df3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b3c6bc-8154-4d09-a401-b5d377d9faa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e004a0fc-65c9-42ac-b42f-d1b71eee502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c714b1d-36d2-45bc-82b6-d34d93466583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47925905-9dc0-4ea6-b46c-b2b5fb83e1af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bf1447c-911b-49f8-b1b3-ea4d39d48d65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_39-UserSamaDanPeriodeSatuMinggu_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a913a9fb-9951-4b86-96d3-20c9b63d8aeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa87250-d3a9-4e6c-b55a-deeb414ab64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8f34ce5-831e-412c-b659-b03281a5be5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1920dffb-bfc3-4353-a5f6-cf3aeda9dc81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8117538-53ce-45d4-a58f-4288a9496f5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d547ebaf-ba93-4f2f-bbe6-ef0c5f691ba1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_40-UserSamaDanPeriodeHariIni_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d71a575e-8556-457c-b223-58625747593d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9acda86f-80fa-426e-ae36-7ae37c9525cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a75e0db1-236b-4974-bb65-dd105d5282f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bb1dc2e-e776-43bc-8e05-057f1e9dce93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a6dcec-9b37-4f8c-bc86-c7ac1b0b8d13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36753b9d-a1ff-4269-96d4-0d3b8424e418</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_41-UserSamaDanPeriodeSatuBulan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688dfc29-7013-4c2b-b75b-d76eaced359e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>685699bc-0901-41dc-96f6-09c30fdba0d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcaed626-2e4a-4864-b75b-90fdaa8e9ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62fe0ab4-8c4a-4d5b-b281-f91499153939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d39f620d-9d61-445f-a011-56c651e97739</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fffb80f0-b470-4c9b-9146-28c1a89c357c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_42-UserSamaPlusUserBaruPeriodeSama_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bd16c28-67e8-4988-be6b-11c50f027cbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f74ec5ef-409c-4932-9a75-4718c7cd0be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2109e8d9-f64b-4b86-9377-96a1a7dbb1c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81817767-5141-4c52-83d8-aae1fd1815a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec5d1a3b-a530-4f93-ab43-afd156b215b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92ea7407-59c5-4f88-8ae9-27a5de671d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_43-POPViewSetupAplikasi_Seccuss</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae146267-f095-42b4-8b8b-6768a026df3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b3c6bc-8154-4d09-a401-b5d377d9faa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea2b30d9-39ff-4101-9ec5-87ce2a47f9a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_44-pengajuanPenataPengendalianOperasionalPDF_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9d58a38-8a67-4b8f-bf3d-9f1b51619ff0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce2d7837-fb4f-4e97-9f33-10519e91699f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065b4af-8ac9-4513-ac9c-34bc832df59a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3270c94d-96fa-453f-a21e-8da6eff01428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_45-pengajuanDicekKepalaOperasional_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1ecb77d-72cd-491d-9eaf-8f7cba798ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b91d39cf-07ee-45b2-87c5-fd91711f823c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e35ac67-3ec2-4dee-94ee-43c70139d38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1532b9f-2383-4b30-a1d3-ae24a7b6bfeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9940b766-de93-4855-8c8f-2c53f57364d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef0c238e-1b85-4cc7-a6c1-cc59806103f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_46-pengajuanDiTolakKAOPS_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21fd1a14-a120-4757-8b29-70b68ebc0cc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00db8053-0cbc-40ea-a353-671b3b8bd1a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b8e2acc-87ac-4fc7-b418-9e4e4ac1a480</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c687b5b-e628-4e59-98de-d2d0feb91d9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6a80c39-c364-459f-9336-d6f36c65d05a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_47-cekdiTolakOlehWAKA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>803a4511-6095-4ed6-aafc-122471bfd4ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec923d38-c58d-45f9-b84a-9b10a32a708d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>330f6c43-981d-4584-b9d6-9c440ed8e86b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba5ac479-c70f-4f6f-805d-4822be229c3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0fe73d-a665-4c69-85c8-05fa5968d556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>257ae86c-297f-4a7e-bfc1-025428c7f7c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_48-cekdiTolakOlehUSMK_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b820f1b0-2a3a-48c6-ad20-f6c0c34adcc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4783728-4f93-4b6c-a994-d23d8058e3d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da1026ab-dd08-4780-97c3-ee36a62457c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21229599-c4e8-4b85-8755-b8971b3ceb1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e035df9-95ed-4e55-831d-1e2f7fd1acaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>837f99db-7152-4c56-8d71-3d2fe0df99a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_49-cekDiTolakOlehUserSelectedCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b30355b6-c4ea-4772-b19d-17bd95f11612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceece0a1-3e9f-4856-965a-5f1c9aae5a6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bc63942-298b-4968-bf05-25517215e5af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a6af179-3a41-40cf-a31b-b07ef21f3d7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b2b57e-05ff-4c0f-8a84-8397ac63217f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c8ef6d5-c262-4b13-8539-d52827521a9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3060c62-e067-438d-a595-92bd24d6827d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_50-penataWilayahViewSetupAplikasi_Seccuss</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41825096-3838-434b-8b88-c4ca53356dc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a14c3465-060d-4bd3-a522-9b697b537e68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>daf23aa7-248c-4519-b297-b0995922cb67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_51-pengajuanStaffWilayahJPEG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9d58a38-8a67-4b8f-bf3d-9f1b51619ff0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce2d7837-fb4f-4e97-9f33-10519e91699f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7065b4af-8ac9-4513-ac9c-34bc832df59a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be3ac737-245c-4334-848d-e812e92f6885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_52-pengajuanDicekKepalaWilayah_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5322ed-e724-4517-b20c-bbc4f813046e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55aa7214-870b-4c54-8053-42ee89407461</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08b24a4b-b51e-4110-90d4-68186fc44ee5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85849a7-76a9-4523-9094-a6d338c60bf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7133eb80-a785-4069-a637-5ef4ad021f04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27d133d3-61ca-4810-9253-8b841f91dac5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_53-pengajuanDiSetujuiKAWIL_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7deaa07e-62ed-41df-85f2-4429f120e11b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7abfc920-6e3f-4711-971b-d696c6bfce0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb5b901-c446-4832-8938-818564b1fa5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24c9000-4471-42ac-a08d-56f966c73517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bc73387-7ffe-459c-b885-a276df1e01c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_54-cekdiSetujuiOlehWAKA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63b33ee4-ba54-44c4-ae70-7be33b602c15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ca646c4-88b4-4721-8d58-af99920de869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>328e0a01-a463-422f-a98e-58696e0efed4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed62bbd-58cf-48fe-8dc4-0439a7e4e511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aa8a3ab-5ac3-412c-8419-8b66d89e035d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d04def30-71b0-49d3-962e-800ad5a791af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_55-cekdiSetujuiOlehUSMK_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04e5fc13-00a1-4a8c-a30e-415758fc2bd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd5d0b6-f939-455a-8d73-46dda8159f5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634af79e-ca52-4164-ab6e-ec2d608f2f3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9012f7-1b59-4013-a302-0d1442239d4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297b2783-67af-4e61-a562-e80dc71b258a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d15da72f-960d-40a4-a0cd-6bf2fd128bda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_56-cekDiSetujuiOlehUserSelectedWilayah_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520db838-66f1-4fdd-87c4-271e1e87eb86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f553bb-1b90-4202-b49b-0fb7af00c02f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e11bd38a-8b2b-450f-a2d4-046ac47584c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb8ecded-54c8-4cb6-b207-16ca0e755806</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2fe920-a400-45a1-ba0f-a1e14dcb8c39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a088a5a-032b-4d81-9ee1-7a90c1c1bb6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be21a015-c45e-45cf-9c64-fdd7ee195c7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_57-kapuViewSetupAplikasi_Seccuss</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93eb7d46-b4e3-4399-a94f-9029588b8f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a4d98d5-173e-460b-9336-c523660cd2c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd99378a-534a-467e-bb88-032bb22bf25c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_58-pengajuanStaffKapuJPEG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b069504a-ac92-452e-93f4-d005e2c3e31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cfddae4-9fe5-4e2f-b1b9-98a7be4b93c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4008f31f-090e-4d79-814f-da31e185cfe5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d193e7c-d88c-4b37-ad1e-1150eca4f538</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_59-loginStaffKAPUSetelahApproved_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7deaa07e-62ed-41df-85f2-4429f120e11b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7abfc920-6e3f-4711-971b-d696c6bfce0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb5b901-c446-4832-8938-818564b1fa5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24c9000-4471-42ac-a08d-56f966c73517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9b93874-8387-4427-8de7-061873c937ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/09-Data Pendukung/01-Setup Akses Aplikasi/SMTC_SetupAksesAplikasi_60-cekdiSetujuiOlehUSMK_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7cacb89-a79d-4384-8953-4623bae04e65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad597877-25ce-4afe-99aa-c8a65f7947e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1102f676-abb3-4543-b084-3b14c8adec11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba530320-b1b1-4019-aa36-979e2899632b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73adf32e-3fdd-4bbf-9011-bc226f80f8ed</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
