#
testRail.password=w73/Pm8VU5viBQUUyejKIDRY4oEifMzaJgPZfNi5Z0N0Zx4pTZ1nUrts0P/Guu+a
testRail.isEncryptionMigrated=true
testRail.isTestRailEnabled=true
testRail.username="dian.samuel@adidata.co.id"
testRail.url="https\://diansamuel.testrail.io/"
testRail.project="1"
