#false.
#@USER username to access database.
#@PASSWORD encrypted password.
PASSWORD=d2VsY29tZTE\=
SECURE_USER_ACCOUNT=true
CONNECTION_PROPERTIES={\n  "connectionProperty"\: [],\n  "props"\: {}\n}
USER=todolist
DRIVERCLASSNAME=
SHOW_WARNING=false
URL=jdbc\:postgresql\://ha.bpjstk.id\:5444/todolist
