#
testRail.password=lgpvLMJUtkb69e5W7zv65NAkpAKMJtlCB6ySyKLcuKwcFOBDRgZhTAYTcHiQaini
testRail.isEncryptionMigrated=true
testRail.isTestRailEnabled=true
testRail.username="dian.samuel@adidata.co.id"
testRail.url="https\://diansamuel.testrail.io/"
testRail.project="1"
