<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Login_01-Aktivasi2FA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d36adc35-5c7e-4e20-a95a-3e8cdf591165</testSuiteGuid>
   <testCaseLink>
      <guid>b6232692-4ea0-44fa-8bde-f7896f9e6f35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_01-view2FA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9c3ecf9-f192-42e4-b19e-5b4698a14073</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c093fce8-860b-440a-8d14-60d0f198347a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>093ba557-0aed-4776-a684-71fdd6053c0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_02-detailAktivasi2FA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3d749277-570c-4f5e-a242-3326ca0addf2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_04-filledAktivasi2FA_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cb559f9-c343-4a42-900e-39a757abb721</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a6ad64-d7c7-4378-b7e1-402ecd82fe09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f09af8cd-ddaa-4d16-a7ea-4b1977c65610</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_05-aktivasi2FAonlyUsername_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>339159b6-9d75-4a64-a479-e8c9329afae0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_06-aktivasi2FAonlyEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5a7fdaa0-b1b8-4c3f-a3f3-98892fc58ce8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_07-unmatchUsernameEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccdd3bb3-af2b-44c8-8a96-c1cf143dd28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a02451b7-e93a-4078-8cb0-0fef594b83ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a5957c1-de70-4516-9e70-4228eb1c8a23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_08-unmatchUsernameEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698f5bf7-e0ce-4690-b544-e0bff0c69576</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a612af6-0f64-47e5-965f-197a509d49e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c26f633-c290-4c7b-a6fb-e8644a9d146a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_09-blankConditionAktivasi2FA-Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5647ce12-7e10-4056-bb2a-b28d4d1959f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_15-kodeUserNotFound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28abb9e-4795-44ae-9b07-2e9407d584ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd84cd21-f6e5-4e1b-9541-9e36f6e803fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c0556da-408f-4317-b7a3-874904605e67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_03-batalAktivasi2FA_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0e574d42-239d-4229-ac8a-ad4613af8de2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_10-Aktivasi2FA-Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb384342-e7bd-4faa-bac1-a2186852ff16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b38abcdd-def6-4c09-9080-6a692103b3c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_11-checkEmail_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eecbc1b-e378-4af3-a13b-6d3607a812b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d49da1-6a07-443b-a18c-bc0d868ade58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2118cd5b-6129-446b-b2bc-87103c894eb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_14-verifikasi2FA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6453c92a-7623-4ae9-a0f3-79d6b82bb099</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20db5773-8c08-4784-beb9-f4a1cbe351a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>934c6e02-786e-415b-9321-cf07a1c6dc54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_12-directSubmitVerifikasi2FA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef52850-6f14-460a-a10a-5eeb904025c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45008184-6f1d-49a6-b951-7b3a8bee7d4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59efbeed-a8a1-4a1b-8547-d97625def472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/01 - Aktivasi 2FA/SMTC_Aktivasi2FA_13-cancelVerifikasi2FA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
