<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Login_02-Overtime</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1917fecb-6956-4765-8043-8df0b4448630</testSuiteGuid>
   <testCaseLink>
      <guid>c115d944-6679-4889-9e16-a4f93aa6ab47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_01-viewOvt_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8f7d8c7a-8416-4afc-94fb-8ded09383b99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_02-viewFormOvt_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b5fc1d83-b3cc-47cf-ab68-8515ce09aa1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_03-directlyPengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3a70d71c-e5d3-4bd2-9a57-42ca760d823a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_04-batalPengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c4cc22c9-6cf3-4cd4-95c2-bbb2ca1bce24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_05-pengajuanOnlyUsername_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>482ac56c-81a3-41d8-b4f2-b204783dcf4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b3971ca-5cc6-4137-8be6-36626e33ef7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_06-pengajuanOnlyEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>213b17d8-f0e7-441d-b463-6d409be5015f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9b33081-7898-4aa3-bb9b-9633e749204e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_07-pengajuanOnlyReason_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9924e87-00e0-466a-992b-d3c1363b50fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54c46dcf-178f-4c42-b0ce-a4cd18bc0b13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_08-pengajuanOnlyUploadFile_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e337d4-e598-4754-9801-495c76eecff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b708f267-b109-4b09-9c64-ecb68c433368</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_09-batalPengajuanToolX_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>67cbaf76-6f06-49df-88d1-296b672eebe9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_10-pengajuanWithoutUsername-Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf52dbb8-e9e9-4f77-a399-f3641b5abdab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d590143-bdeb-4ec6-8731-faba4a1c234b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a73565-7307-40a0-8793-f6d138653f6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b8578e0-0515-4890-bf9f-886637dbdb3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_11-pengajuanWithoutEmail-Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7205e90b-293b-4749-92f2-c452f7994f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604f02b2-5031-406a-90a2-dd9576d8fe2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb21034d-fbe1-40e1-be84-6a0ef50b399c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ddd35ac-fb18-43e6-ab70-f227f4886169</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_12-pengajuanWIthoutReason_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64260533-ebec-410f-95a3-e944f04a6a02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99dbe550-ffb2-42cf-8086-cbe4277cc33e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e485fe7-1635-4122-8eaa-d8a5f48177bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>401ff2b2-bec1-49aa-8b8f-78649cdf274a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_13-pengajuanWithoutFile_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daadae64-7f66-4c42-9b2d-bc7906c8bf89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c9ca28-3e87-49c0-bb3e-6eac7f6423d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9fcad17-a01e-4bc6-aefa-bbc5443b717d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86df9f41-fbbd-45b8-8f9c-0dd02b9bf04c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_14-pengajuanWithInvalidEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85ad4bc-fe40-4eac-8e15-91e6626e91a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f732add3-8b7b-4789-84bd-7d2192816d46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bfae283-0128-441d-a49f-c160736ee42d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a5fa23-ae87-4a8a-8cbd-9edac26f8f69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de06d8c5-5a13-40c8-bbd0-921efe5f6998</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_15-pengajuanWithEmailNonBPJSTK_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f00b28-fb4c-4ff8-ae30-55c4bc7d69ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1fba67a-b03e-4744-9447-ab42c6c575df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521920e4-a8a8-4eb7-b384-d9d82bc37418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd59492-ae08-4522-81b8-666ebe6d6e19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72c51c2b-535f-4468-acea-042276a37bd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_16-pengajuanwithFilePDFUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5500c505-ad1e-4c01-8e99-d560aeee8c91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31273df6-5ab4-421a-88f1-44c84798f8ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_17-pengajuanWithInvalidFileXlxs_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cae8742-f247-4f97-86f8-6e2da915faaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>873ca42f-c35e-4e20-ba42-bb5d41e10d97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_18-pengajuanwithFileJPGUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f32ba2f-d223-408d-8fbe-5cf3159b52a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da17063c-dd6e-42e6-b09b-be8d8da99939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_19-pengajuanwithFileJPEGUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>833b5e0c-77cf-4705-8ae5-8e8de063c66a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d99a2e80-d666-4467-8a9f-964ee423e660</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_20-pengajuanwithFileXlxsUpto2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a86905-9dec-47fb-8963-99a86dac16b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9c2c5d1-9a1b-4a50-af17-5d7b33d2f1e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_21-pengajuanOvertimeJPG_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4322fed-e0ad-4be9-80c1-ffcfd6892705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b9f17cf-b898-40a3-9532-d559777178f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b70d18-1e97-4fde-a7a9-d1c8a019fdd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1367cba-d01f-45ff-afef-af191e6bf2c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>336ea60d-dabf-4386-9eac-c716a256f630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8054c89-3cb3-4aff-a4cf-8c81bb497169</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
