<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Overtime_03-pengajuanOlehKCP</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>048d8373-e63b-4a25-af68-22c6448cc82e</testSuiteGuid>
   <testCaseLink>
      <guid>f7dc4296-2889-4bce-a82a-ffebfc757834</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_32-pengajuanPDFStaffCabangKCP_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4322fed-e0ad-4be9-80c1-ffcfd6892705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b9f17cf-b898-40a3-9532-d559777178f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b70d18-1e97-4fde-a7a9-d1c8a019fdd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1367cba-d01f-45ff-afef-af191e6bf2c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>336ea60d-dabf-4386-9eac-c716a256f630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8054c89-3cb3-4aff-a4cf-8c81bb497169</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcdfc1b9-6cd8-4328-9716-ee152d4f527b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>390f7a10-89f9-479f-bf8f-19492c3ce7d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_33_LoginOvertimeBelumDisetujui_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfce47d5-b747-4d2d-88d3-27ecc8cf84d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b405796-27c7-44a4-ba46-b6d385cda7d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88408175-8925-4af4-aad2-45c6a6d97f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_34-pengajuanDitolakKepalaUnit_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30dabddb-7461-453c-8e54-84087153a6e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26e030a5-cc3f-4ee8-a3f4-1f9d79d961ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0df2625-2659-4433-8370-ff328905a9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35367558-557f-4998-98ca-d941a87dc25f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8218c8c0-b7c2-4281-a83a-2d9e508d93a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_35-cekDitolakOlehStaffCabangKCP_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd3d5928-a25e-4870-afec-c3423be89910</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_36-pengajuandiCekOlehWAKAdariKACABKCP_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4ddadc9-7328-42bb-81aa-727617de1f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_37-pengajuanCekOlehUSMKdariKACABKCP_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
