<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Overtime_04-pengajuanOlehWilayah</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d49ff7a4-4474-4732-9be4-d20b80a9f38b</testSuiteGuid>
   <testCaseLink>
      <guid>07f1acf7-fca2-4dab-b02b-9b46b6e3affb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_38-pengajuanJPEGStaffWilayah_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4322fed-e0ad-4be9-80c1-ffcfd6892705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b9f17cf-b898-40a3-9532-d559777178f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b70d18-1e97-4fde-a7a9-d1c8a019fdd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1367cba-d01f-45ff-afef-af191e6bf2c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>336ea60d-dabf-4386-9eac-c716a256f630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8054c89-3cb3-4aff-a4cf-8c81bb497169</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcdfc1b9-6cd8-4328-9716-ee152d4f527b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>999bf5cc-dded-41cf-a83f-c564ec32479f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_39-pengajuanDisetujuiKepalaWilayah_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30dabddb-7461-453c-8e54-84087153a6e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26e030a5-cc3f-4ee8-a3f4-1f9d79d961ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0df2625-2659-4433-8370-ff328905a9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35367558-557f-4998-98ca-d941a87dc25f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74b1274a-d372-499f-b559-5b016e8d4180</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_40-cekDisetujuiolehStaffWilayah_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1949baf-5b38-4e59-85e4-5bd1773b9370</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_41-pengajuandiCekOlehWAKAdariKANWIL_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2a90caf-848d-4b83-8254-afd918bd09c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>034ebce3-ccc1-4662-9427-4d207815f8af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>824c13bb-b626-4e2f-9a12-493d4ef439dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>525268e5-1df9-4579-8090-4d3c2dc73691</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc53fc57-8aa6-451f-8be2-0896e3e67a6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3fa685e-e787-46db-b35b-99bf45fe71a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_42-pengajuanCekOlehUSMKdariKANWIL_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6fdddbf-7b6d-41d2-87fe-550e128be747</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>476dac75-f0ec-491e-891e-1b7e51eb65b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91efe9e5-887f-4e75-a20c-9cf3e8255adc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcaf1fd6-fb37-435b-b96c-433a386b8a62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff97bac-d695-43b3-ab02-7d88d78b298b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
