<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Overtime_01-Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1917fecb-6956-4765-8043-8df0b4448630</testSuiteGuid>
   <testCaseLink>
      <guid>036ec162-896d-4635-a707-854d89fbc900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_01-viewOvt_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>31695616-0cd1-4d84-9d7e-ef9361f290e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_02-viewFormOvt_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b3202715-66c2-4c07-83a8-07bf9e91f6db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_03-directlyPengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>349c17a9-a4f7-4515-8bc1-681f00201f4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_04-batalPengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>397e59dd-73ab-4ef9-8a9d-189715376dd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_05-pengajuanOnlyUsername_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>482ac56c-81a3-41d8-b4f2-b204783dcf4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb50f7b7-a0a4-471e-bc24-5b656b4ba6cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_06-pengajuanOnlyEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>213b17d8-f0e7-441d-b463-6d409be5015f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30159b72-fdc8-4535-9306-f4771718fdcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_07-cekPeriodePengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2e54bbc9-8630-442b-8682-e7a8817f5a68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_08-pengajuanOnlyReason_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9924e87-00e0-466a-992b-d3c1363b50fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>850fa2b0-c994-4596-bb17-acdde663ab69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_09-pengajuanOnlyUploadFile_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e337d4-e598-4754-9801-495c76eecff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d144b9b2-5d11-4b6d-8caf-f33bf55d2042</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_10-klikTombolX_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4a72cf57-94b5-4990-8da6-192969340488</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_11-pengajuanWithoutUsername_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604f02b2-5031-406a-90a2-dd9576d8fe2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb21034d-fbe1-40e1-be84-6a0ef50b399c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37e8b645-a78a-4555-9552-f7e7e7771c8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cba0b93-74de-4602-a421-02843ded687f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_12-pengajuanWithoutEmail-Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7205e90b-293b-4749-92f2-c452f7994f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604f02b2-5031-406a-90a2-dd9576d8fe2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb21034d-fbe1-40e1-be84-6a0ef50b399c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b571cd8-1297-4904-8eee-68e828b48d7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_13-pengajuanWIthoutReason_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64260533-ebec-410f-95a3-e944f04a6a02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99dbe550-ffb2-42cf-8086-cbe4277cc33e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e485fe7-1635-4122-8eaa-d8a5f48177bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cf97d76-a20e-4a40-80a1-ae2a8bfe3891</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_14-pengajuanWithoutFile_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daadae64-7f66-4c42-9b2d-bc7906c8bf89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c9ca28-3e87-49c0-bb3e-6eac7f6423d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9fcad17-a01e-4bc6-aefa-bbc5443b717d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>840fde09-d38b-496a-a8cd-c65d8084476a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_15-pengajuanUsernameNotRegistered-Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46aa8021-30b7-4bad-8df3-8dd7006f63e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f3f2f08-fe73-4ac7-849f-f7d815688a2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0585375-0057-4490-ba89-9bc8bf91b654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5a612a1-e333-4c27-87fd-fb5379cc1780</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f344a0d-8efb-43b4-a02a-1b18828b2e2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_16-pengajuanWithEmailNonBPJSTK_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f00b28-fb4c-4ff8-ae30-55c4bc7d69ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1fba67a-b03e-4744-9447-ab42c6c575df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521920e4-a8a8-4eb7-b384-d9d82bc37418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd59492-ae08-4522-81b8-666ebe6d6e19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>718d302c-873f-40fe-b327-ccbb2d6f0ef2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_17-pengajuanWithInvalidEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85ad4bc-fe40-4eac-8e15-91e6626e91a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f732add3-8b7b-4789-84bd-7d2192816d46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bfae283-0128-441d-a49f-c160736ee42d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a5fa23-ae87-4a8a-8cbd-9edac26f8f69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d5e49f7-bfb0-4776-8f44-d02f1a2e980c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_18-pengajuanWithInvalidFileXlxs_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cae8742-f247-4f97-86f8-6e2da915faaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76323488-a3d0-45df-bd28-2a91cd5e83e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_19-pengajuanwithFileXlxsUpto2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a86905-9dec-47fb-8963-99a86dac16b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa9ab9df-16f4-4b8a-ae0b-2aca5aff2067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_20-pengajuanUnmatchUsernameNEmail_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27e68974-1a98-428c-84c5-95ed7a3f04c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89fccd3-b261-48be-b665-d97793beb164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50d4b913-a1be-4dfe-93a3-743efd53acdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca71ee43-7e12-409f-bd77-c80794dd1fe2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e22ec7b-b098-44ac-b726-5ab2c5b9ef6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_21-pengajuanwithFilePDFUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5500c505-ad1e-4c01-8e99-d560aeee8c91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>446aa5a1-f501-43e5-b21e-051eeced8415</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_22-pengajuanwithFileJPGUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f32ba2f-d223-408d-8fbe-5cf3159b52a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36daaa9c-952e-4b35-b61a-4d9ca5c4bf14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_23-pengajuanwithFileJPEGUpTo2MB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>833b5e0c-77cf-4705-8ae5-8e8de063c66a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66290d71-1dcc-40b2-bcc6-0909d02d6b59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_24-loginTanpaPengajuan_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
