<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_Overtime_02-pengajuanOlehCabang</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3c16f3b0-bec4-43b3-9e44-44a4892331d9</testSuiteGuid>
   <testCaseLink>
      <guid>432c4567-7e65-4cd4-b211-900267845e9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_25-pengajuanOvertimeJPGStaffCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4322fed-e0ad-4be9-80c1-ffcfd6892705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b9f17cf-b898-40a3-9532-d559777178f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b70d18-1e97-4fde-a7a9-d1c8a019fdd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1367cba-d01f-45ff-afef-af191e6bf2c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>336ea60d-dabf-4386-9eac-c716a256f630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8054c89-3cb3-4aff-a4cf-8c81bb497169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bf332f8-42df-4b98-8ba3-31a460411b61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_26-pengajuanKembaliStaffCabang_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97d7d45a-ede0-42ae-a307-626c40db3d6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79b116ae-21b3-41ac-b4f9-f4db5b4678de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae14df15-a4c7-4f4b-94a0-a3a340bc8f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>214645b7-8bf9-449c-bc35-46bba8689a6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7773cfb-329b-4d23-a91d-bfb9cc4350b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_27-pengajuandiCekKepalaCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fbc9865-15ca-4259-9a2c-c79b50764323</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ae1e40d-7457-43ea-aaa5-f16e5693ee84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4174883e-8bcc-48e6-bde8-1b465f12709d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c0af19b-2e0d-4c59-9bc2-effd460cbbeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d1b50a-6e3a-4272-8f26-6e1f41754b1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b01e9cad-887f-4cac-b0ac-5a3f77436462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9c95d55-48cd-4165-88d8-4875947d6c60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d788d00f-97b6-45ee-885c-bbc34b375ee6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_28-pengajuanDisetujuiKepalaUnit_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30dabddb-7461-453c-8e54-84087153a6e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26e030a5-cc3f-4ee8-a3f4-1f9d79d961ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0df2625-2659-4433-8370-ff328905a9fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35367558-557f-4998-98ca-d941a87dc25f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20a1066c-bd21-4c0e-8344-28bd481ddb8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_29-cekDisetujuiolehStaffCabang_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64488179-fad8-468e-8ba2-a02d9509b2aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_30-pengajuanCekOlehUSMKdariKACAB_Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f576e96-4b1e-46e2-a411-584fcbe5469f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01-Login/03 - Overtime/SMTC_Overtime_31-pengajuanCekOlehWAKAdariKACAB_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92f82c8-190b-43d4-ad57-262921159660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c166a279-c969-4f77-9d31-931ccb4c24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dc40b4-bef2-4a9d-9a51-05d81d04920d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d841d4-89b1-490b-8aea-84fdc7adc121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6520c7eb-56a7-4e8c-8785-31050ff240d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
