<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SMTS_kpiKantorDaerah</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ff163a05-d7c6-4281-beec-2d0293459b63</testSuiteGuid>
   <testCaseLink>
      <guid>7d9a4965-dff9-4e65-8f87-2ac82ade1c07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_01-PapanKinerja</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa776a3c-d4bf-4042-b724-b5f6f70ea4ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06cbcbd2-9111-42ad-9414-3dce8ddb7db5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ed7fe52-e18e-4ca9-b78b-73e41492ea0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fd74cad-fb8f-4641-b422-b0fa6fdcdfba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba9e3930-65bf-48ed-977e-2ace23f78b98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77700408-7cac-400a-9f9e-28dc5dbc9416</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a46ad3e-4b4b-4898-92b7-6c6507525c56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3398a103-7323-4616-91c7-9840bbcf5c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f9aa717-7a2b-4371-b005-91df621ff1bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20bfea01-4580-4353-9292-9619cb0c1617</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_02-Peringkat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc55d9b8-e850-4f03-93a0-def5b8f204c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b001a593-cbab-4968-8db7-923890a3e5a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c58ad21-9e6e-483c-83bc-8978bf251a83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bbe7cdb-a5ba-44b2-bc9d-fc01f376db60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246773a3-731a-4706-8580-6b10a8a47a61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d62c402-8433-4f6a-b805-00ed6d52931a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_03-PeringkatbyIndikator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4ccdf12-acf0-46a3-bdbe-e94f2cf69c1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce897a8-d7d5-4ecb-b38e-48aadcb47aeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56824d5b-c45d-4010-8f75-2168644e7209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>076bb14a-1437-4965-83f8-37e1c53fd3f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76869b85-b305-435e-bdcd-4dcb90efec31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>280e1b9c-22f8-46c5-9382-13fcc9dd4895</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88f811a1-c803-427f-8324-d5cc260deead</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_04-Top10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79381bda-f850-4ba5-9af3-dd3c8e0bfe2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d42cb46-b214-4011-853c-24e0eabb69a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25ea8ffd-dd1a-43fa-95ca-81b149a4d16d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_05-Worst10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6826d1aa-614e-4b37-8c9f-eaba024d65c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c75e030-09fa-4921-8b1a-088eb8795784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2da96b8-a3b4-4700-9544-d14ebf0e6ec0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_06-Komparasi Kinerja</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e68887-949c-4571-847c-6462c2f72139</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3503e6e5-6566-4efc-9ad1-2ad412fbb3fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb4c3b3-84e1-4101-97ea-8642c7853cc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b82cff17-1732-4a0c-b1a6-2e09c6a8216a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c476e0-f696-4822-803a-6956d4dc4fc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c304b1-50ba-46a6-95c0-cd15b8f8249e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>782d6e81-a9e8-4f24-9af3-909c4e0c9497</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_07-Simulasi Kinerja</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb9882f2-57d8-442e-961a-0d5236d779f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80f7891d-7b09-4c35-bd81-14922d361ad4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26561f76-9b94-4a05-a45e-054ed2683f2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>897f74c0-8e81-405a-a581-75352164ed65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/02-Menu/13-Performance Management/Key Performance Indicator/SMTC_KPI_08-Overview</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e83861c-dbef-482a-901a-888d11f5bbd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efa68227-afc5-47ca-b713-868838e1e0c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eef1063-46f7-4a6a-8a3e-f349125b56e5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
