<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_kodeKantor</name>
   <tag></tag>
   <elementGuidId>c3480304-83cc-4ea1-85e8-b097cd0de6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td//a[text()=&quot;${param}&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
