<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2024</name>
   <tag></tag>
   <elementGuidId>ffe8e257-9156-469d-9fe6-60b93e5c1d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-picker__title__btn.v-date-picker-title__year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[.='2024']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2024&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cf6036b-12ab-4f85-a965-5980a3d09cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-picker__title__btn v-date-picker-title__year</value>
      <webElementGuid>bd239266-7341-4769-9fc4-d6b604448922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>e720f6ee-a106-4541-9500-da136bcfede2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-menu__content theme--light menuable__content__active&quot;]/div[@class=&quot;v-picker v-card v-picker--date theme--light&quot;]/div[@class=&quot;v-picker__title primary&quot;]/div[@class=&quot;v-date-picker-title&quot;]/div[@class=&quot;v-picker__title__btn v-date-picker-title__year&quot;]</value>
      <webElementGuid>a130ad01-4cbc-4f78-8094-88ad41493e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div</value>
      <webElementGuid>3d38f5fb-f237-453f-8e95-bf40d3cfbc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPJS Ketenagakerjaan'])[1]/following::div[5]</value>
      <webElementGuid>69690773-86ac-48f9-a861-88bb3cdd98b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December 2024'])[1]/preceding::div[3]</value>
      <webElementGuid>560aff0f-888a-46a2-9a97-600e7483f666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::div[6]</value>
      <webElementGuid>b9bdcb02-05a1-4fa5-8715-ed2ccd022e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>09eede18-5c27-42d3-aaa2-e179cd7878a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>2d83aea2-b01f-459f-8847-b7d4dcff7997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2024' or . = '2024')]</value>
      <webElementGuid>6e348071-69d7-473e-b177-a6524ef80e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
