<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element Penawaran</name>
   <tag></tag>
   <elementGuidId>976544e0-66f6-4e40-9dcb-fcb9f84145dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='core-view']/div/div/div/div/div[2]/div/form/div/h2[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.font-weight-bold.mb-4.mt-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Penawaran&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d0d2f46d-70de-4671-bb74-cb38e6347042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold mb-4 mt-5</value>
      <webElementGuid>d0937cca-204f-4a54-b003-dd93b23a769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penawaran</value>
      <webElementGuid>24fe66fa-083d-4977-8e16-f08b40e98575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;core-view&quot;)/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;row pb-10 justify-center&quot;]/div[@class=&quot;col-md-12 col-12&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[1]/form[@class=&quot;v-form&quot;]/div[@class=&quot;col-lg-6 col-12&quot;]/h2[@class=&quot;font-weight-bold mb-4 mt-5&quot;]</value>
      <webElementGuid>7069bc5e-5f76-4089-891e-7900957a1346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='core-view']/div/div/div/div/div[2]/div/form/div/h2[2]</value>
      <webElementGuid>d5dd70c3-cbb5-462f-9deb-a1222d55f779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pekerjaan'])[1]/following::h2[1]</value>
      <webElementGuid>d9186f18-951e-4126-a743-5bfb7d60a91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::h2[1]</value>
      <webElementGuid>86a39706-812d-4363-8aa8-772ff0431516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/preceding::h2[1]</value>
      <webElementGuid>e176d21c-72f2-4d1b-bd41-143cd90b6e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Penawaran'])[1]/preceding::h2[1]</value>
      <webElementGuid>398d7eb7-249c-4f61-8020-9de737e17f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penawaran']/parent::*</value>
      <webElementGuid>1bf7f781-04a1-4afb-afd6-b63694746141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h2[2]</value>
      <webElementGuid>6d94adaa-a215-4327-9438-6d7611170fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Penawaran' or . = 'Penawaran')]</value>
      <webElementGuid>418211e8-98fa-4840-9ad1-f1cf4bcce118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
