<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hari</name>
   <tag></tag>
   <elementGuidId>bf5d8e63-240f-4aed-bc2e-cd3d2321632c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='v-list v-select-list v-sheet theme--light theme--light']/div[@class='v-list-item v-list-item--link theme--light']/div[.='Hari']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Hari&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef8bf840-5063-447f-bb07-ef514cc45354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>120cb918-3a41-404f-b592-dc203eb58392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hari</value>
      <webElementGuid>25004c69-e8a3-47d3-9095-a3808ba7464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-259-0&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>246663a6-7dc7-423d-a4ee-a6734ab66583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-259-0']/div</value>
      <webElementGuid>b0dc1ae8-c2d4-41e8-8459-903a8062d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPJS Ketenagakerjaan'])[1]/following::div[4]</value>
      <webElementGuid>562b897f-b6fb-4e58-80b8-8cc7bc7bb321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minggu'])[1]/preceding::div[2]</value>
      <webElementGuid>2150f76e-81de-4ab9-9c4b-fd10354c2e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>f643736b-1c17-4792-ae13-843253a818fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hari' or . = 'Hari')]</value>
      <webElementGuid>fa3c0edf-f3b3-48d6-b83e-1a8498527846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
