<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Beranda_v-icon notranslate mdi mdi-bell t_7f292f</name>
   <tag></tag>
   <elementGuidId>8bee1ecf-2b8c-4eee-bd63-bc454bcc0697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='core-app-bar']/div/div[3]/div/button/span/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.mdi.mdi-bell.theme--light.tertiary--text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Badge&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>67e94a03-4c4d-4f6a-9d3f-7264b4e6bb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3248cb55-c9cb-422b-b552-eb71505728c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-bell theme--light tertiary--text</value>
      <webElementGuid>1a6618a7-cdcf-4966-99ea-f8b4a9b9b6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;core-app-bar&quot;)/div[@class=&quot;v-toolbar__content&quot;]/div[@class=&quot;v-toolbar__items&quot;]/div[@class=&quot;row mx-0&quot;]/button[@class=&quot;toolbar-items v-btn v-btn--icon v-btn--round theme--light v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/span[@class=&quot;v-badge v-badge--overlap theme--light&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-bell theme--light tertiary--text&quot;]</value>
      <webElementGuid>478bb06d-15f2-48a1-82df-8bf59a42e0cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='core-app-bar']/div/div[3]/div/button/span/span/i</value>
      <webElementGuid>4893791a-480d-4564-93c1-9474e31a3948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>a8459836-e493-4eb8-898b-ae986dd1b652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
