<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe berikutnya dan verifikasi</name>
   <tag></tag>
   <elementGuidId>1758076c-3fb9-4be3-9537-d3bdebe996ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-xwpq2ya7uytj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-xwpq2ya7uytj&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-xwpq2ya7uytj&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>964fcc5c-5d80-45ab-884b-1ed570707915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>masa berlaku tantangan recaptcha akan berakhir dalam dua menit</value>
      <webElementGuid>1f46a48d-64ac-4c6b-8660-7e4d31fc4829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-xwpq2ya7uytj</value>
      <webElementGuid>e85afa19-eecf-4284-9846-d17fd181752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59019ca4-308b-41a3-b9b1-19066ef82803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8e9098f9-88b9-440d-b561-2ec9d345e659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>099f3512-5ab2-4bfb-8556-a7dbab807eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;k=6LdIF0cdAAAAAL6rVy3H7hoFHb4f59VE_Msv_xxT</value>
      <webElementGuid>d2bdfb92-3f14-4f26-9c1b-18d5fc8f615d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>47d479ca-d536-4ae3-b217-f8d71c7d4be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-xwpq2ya7uytj']</value>
      <webElementGuid>dc285855-7b3e-4b6c-977c-67efa833a2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>95b455e9-b6b6-4a45-9ff6-fb4f03297423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'masa berlaku tantangan recaptcha akan berakhir dalam dua menit' and @name = 'c-xwpq2ya7uytj' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;k=6LdIF0cdAAAAAL6rVy3H7hoFHb4f59VE_Msv_xxT']</value>
      <webElementGuid>7655513f-dec4-47b7-a6b0-02bfb4704488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
