<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input nama notif pengadaan</name>
   <tag></tag>
   <elementGuidId>9ee3a4a5-9400-46ad-8503-3a954bebbe40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/main/div/div/div/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-106</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f45c0a93-c0bf-4210-80d8-751d1d7b4511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-106</value>
      <webElementGuid>8e234083-d7e4-40ef-bd7d-ae5e1b567adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecd24487-8017-4591-8967-da95825cd457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-106&quot;)</value>
      <webElementGuid>e6c19f21-d359-4adb-bf0b-88b739c9e24a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-106']</value>
      <webElementGuid>25649eb7-6ef5-4506-a239-039cd2dee726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='core-view']/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9fecd751-99ab-4f80-a561-e8be2eb7123f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dc660893-a6b7-47c1-ab4a-de82d5aaa790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-106' and @type = 'text']</value>
      <webElementGuid>ae07e53f-2b1d-403b-81f7-d7b1264d15ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
